name: Build and Run Game

on:
  push:
    branches:
      - main

jobs:
  build_and_run_game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Xvfb
        run: sudo apt-get install xvfb

      - name: Build and Run Game
        run: |
          xvfb-run -a python game.py
