name: txt files check

on:
  push:
    branches:
      - main

jobs:
  txt_file_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run txt file check
        run: python txtchecks.py



