name: Text Files Check

on:
  push:
    branches:
      - main

jobs:
  txt_file_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run txt file check
        run: |
          txt_files=$(find . -name "*.txt")
            
          for file in $txt_files; do
            
            lines=$(cat "$file" | wc -l)
            
            if [[ $lines -eq 24 ]]; then
              while IFS= read -r -d '' -u 3 line; do
                if [[ ${#line} -gt 59 ]]; then
                  echo "Line in file $file exceeds the maximum length of 59 characters."
                  exit 1
                fi
              done 3< <(iconv -f UTF-8 -t UTF-8 -c < "$file" && printf '\0')
            
              echo "File $file has the correct number of lines and line lengths."
            else
              echo "File $file does not have the correct number of lines."
              exit 1
            fi
          done
