name: txt files check

on:
  push:
    branches:
      - main

jobs:
  txt_file_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run txt file check
        run: |
          python3 - << EOF
          import os

          def check_txt_files():
              repo_root = os.environ['GITHUB_WORKSPACE']
              txt_files = [file for file in os.listdir(repo_root) if file.endswith('.txt')]

              for file in txt_files:
                  file_path = os.path.join(repo_root, file)
                  with open(file_path, 'r', encoding='utf-8') as f:
                      lines = f.readlines()
                      if len(lines) == 24:
                          for line in lines:
                              if len(line.rstrip('\n')) > 59:
                                  print("::error::Line in file {} exceeds the maximum length of 59 characters.".format(file))
                                  exit(1)
                          print("File {} has the correct number of lines and line lengths.".format(file))
                      else:
                          print("::error::File {} does not have the correct number of lines.".format(file))
                          exit(1)

          if __name__ == '__main__':
              check_txt_files()
          EOF
        shell: bash
