name: Check Wheel Package

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Check wheel package installation
        run: pip install wheel\ package/dist/*.whl

      - name: Run wheel
        run: pacman || (exit_code=$?; if [ $exit_code -ne 0 ] && [ $exit_code -ne 126 ] && [ $exit_code -ne 127 ]; then exit $exit_code; fi)
